openapi: 3.0.4
info:
  title: project-management-api
  description: ## REST API for a project management application
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description:
  
paths:
  /projects:
    get:
      summary: Returns a list of projects.
      description: ### Updated projects list
      responses:
        "200": # status code
          description: A JSON array of user projects
          content:
            application/json: 
              schema:
                type: array
                items:
                  type: string