openapi: 3.0.4
info:
  title: Project Management API
  description: REST API for a project management application
  version: 1.0.0
servers:
  - url: http://localhost:2018/
    description: API server

paths:
  /projects:
    get:
      summary: Returns a list of projects
      responses:
        "200":
          description: A JSON array of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
